apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    app: db
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    container:
      name: db-d
      image:  mongo-express:latest
      command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"            
      ports: 
        - containerPort: 27017 
      env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:  
            secretKeyRef:
              name: secret
              key:  username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key:  password 
          volumeMounts:
            - name: mongo-vol
              path: /data/db
      volume: 
        